config/routes.rb
Rails.application.routes.draw do
  resources :invitations

  get 'welcome/index'

  root 'welcome#index'

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: [:show, :edit, :update, :destroy]

  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = Invitation.all
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # GET /invitations/1/edit
  def edit
  end

  # POST /invitations
  # POST /invitations.json
  def create
    @invitation = Invitation.new(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to @invitation, notice: 'Invitation was successfully created.' }
        format.json { render :show, status: :created, location: @invitation }
      else
        format.html { render :new }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitations/1
  # PATCH/PUT /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    @invitation.destroy
    respond_to do |format|
      format.html { redirect_to invitations_url, notice: 'Invitation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invitation_params
      params.require(:invitation).permit(:name, :phone, :gift, :hotel, :party, :note)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :gift %><br>
    <%= f.text_field :gift %>
  </div>
  <div class="field">
    <%= f.label :hotel %><br>
    <%= f.text_field :hotel %>
  </div>
  <div class="field">
    <%= f.label :party %><br>
    <%= f.text_field :party %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<h1>Listing invitations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Gift</th>
      <th>Hotel</th>
      <th>Party</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
      <tr>
        <td><%= invitation.name %></td>
        <td><%= invitation.phone %></td>
        <td><%= invitation.gift %></td>
        <td><%= invitation.hotel %></td>
        <td><%= invitation.party %></td>
        <td><%= invitation.note %></td>
        <td><%= link_to 'Show', invitation %></td>
        <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @invitation.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @invitation.phone %>
</p>

<p>
  <strong>Gift:</strong>
  <%= @invitation.gift %>
</p>

<p>
  <strong>Hotel:</strong>
  <%= @invitation.hotel %>
</p>

<p>
  <strong>Party:</strong>
  <%= @invitation.party %>
</p>

<p>
  <strong>Note:</strong>
  <%= @invitation.note %>
</p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">

    <!--[if lt IE 9]>
    <script src="assets/html5shiv.js"></script>
    <script src="assets/respond.min.js"></script>
    <![endif]-->

	<link rel="shortcut icon" href="images/favicon.png">
	<link href="assets/bootstrap.css" rel="stylesheet">

    <title>Oh My Love</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <script src="http://ditu.google.cn/maps/api/js?language=zh&key=AIzaSyDoVGqulpbHYNWy0J90gZkgW9kBkzg7ook"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>

  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/welcome/_form.html.erb
<%= form_for(@invitation, remote: true, html: {id: "invitation-form", class: "form-horizontal", role: "form"}) do |f| %>
<% if @invitation.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

  <ul>
    <% @invitation.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <label for="invitation_name" class="col-md-2 control-label">恭请</label>
  <div class="col-md-10">
    <input type="text" class="form-control" id="invitation_name" name="invitation[name]" placeholder="您的大名" required>
  </div>
</div>
<div class="form-group">
  <label for="invitation_phone" class="col-md-2 control-label">手机</label>
  <div class="col-md-10">
    <input type="text" class="form-control" id="invitation_phone" name="invitation[phone]" placeholder="怎么联系您" required>
  </div>
</div>
<div class="form-group">
  <label for="invitation_gift" class="col-md-2 control-label">备礼</label>
  <div class="col-md-10">
    <select id="invitation_gift" class="form-control" name="invitation[gift]">
      <option value="card">寄贺卡</option>
      <option value="debt">打欠条</option>
    </select>
  </div>
</div>
<div class="form-group">
  <label for="invitation_hotel" class="col-md-2 control-label">住宿</label>
  <div class="col-md-10">
    <select id="invitation_hotel" class="form-control" name="invitation[hotel]">
      <option value="none">none</option>
      <option value="yes">安排住宿</option>
      <option value="no">不安排住宿</option>
    </select>
  </div>
</div>
<div class="form-group">
  <label for="invitation_party" class="col-md-2 control-label">场次</label>
  <div class="col-md-10">
    <select id="invitation_party" class="form-control" name="invitation[party]">
      <option value="none">none</option>
      <option value="bride">家宴：2014年9月20日11:00-14:00，浙江省台州市天台县左岸酒店</option>
      <option value="groom">婚礼：2014年10月1日10:00-14:00，河北省承德市宽城县鑫河饭店</option>
    </select>
  </div>
</div>
<div class="form-group">
  <label for="invitation_note" class="col-md-2 control-label">留言</label>
  <div class="col-md-10">
    <textarea type="text" class="form-control" id="invitation_note" name="invitation[note]" placeholder="借您吉言"></textarea>
  </div>
</div>
<div class="form-group">
  <div class="col-md-offset-2 col-md-10">
    <button type="submit" class="btn btn-success">祝福</button>
  </div>
</div>
<% end %>

app/views/welcome/index.html.erb
<div class="preloader"></div>
<audio preload="auto" id="music" autoplay loop>
  <source src="music/karunesh_follow_your_heart.mp3" type="audio/mp3" />
  <source src="music/karunesh_follow_your_heart.ogg" type="audio/ogg" />
</audio>

<! -- ******************** MASTHEAD SECTION ******************** -->
<main id="top" class="masthead" role="main">
  <div class="container">
    <div id="map-canvas"></div>
    <div id="story-caption">Love Story</div>
	<p class="scrollto--arrow"><img src="images/scroll_down.png" alt="scroll down arrow"></p>
  </div><! --/container -->
</main><! --/main -->

<! -- ******************** TESTIMONIALS SECTION ******************** -->
<div class="highlight testimonials">
  <div class="container">
	<div class="section-title">
	  <h2>相识</h2>
	</div>

	<section class="row breath">
	  <div class="col-md-6">
		<div class="testblock">
          <p>
            时光真的是件很神奇的事儿，昨日还在细数孩童时期的美好回忆，今番已然要开始承担组建新家庭的责任---不经意间我们都已长大成人，要开始新的征程了。
          </p>
          <p>
            小时候看着山谷里的狭长蓝天，就想变成天上的鸟儿，飞出去看看外面的世界有多宽广；见到了城市里灰蒙蒙的天空，就想着下辈子做条海里的大鱼吧，远离尘世的喧嚣繁杂，在蓝色净流中自在翱翔。从山村到城市，从家乡到异地，向外探寻的征程中有过迷茫，有过挣扎，十几年的孤单闯荡后幸运地遇见了想变成大鸟的他，同样是大山的孩子，有着岩石般的坚韧与泥土般的朴实，但都怀抱畅游世界的志向。<strong>行走，思考，在路上</strong>，好像很自然的，我们就走到了一起。
          </p>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_m.png" alt=".">
		  <p><strong>妞</strong></p>
		</div>
	  </div><! --/col-md-6 -->

	  <div class="col-md-6">
		<div class="testblock">
          他是她的初恋，她也是<br>
          他是大山的孩子，她也是<br>
          他，呆头呆脑；她，傻里傻气<br>
          18岁的他，踌躇满志，对未来充满期待，立志以纸笔为舟桨在科学的海洋里尽情探索<br>
          18岁的她，少女初成，对生活一片憧憬，想要用墨彩为颜料在生活的画布上肆意涂鸦<br>
          未曾想<br>
          他遇到了她，她遇到了他<br>
          <strong>所谓相识，懵懂悸动</strong><br>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_x.png" alt=".">
		  <p><strong>爷</strong></p>
		</div>
	  </div><! --/col-md-6 -->
	</section><! --/section -->

  </div><! --/container -->
</div><! --/highlight Testimonials -->

<!-- testimonials 2 -->
<div class="testimonials">
  <div class="container">
	<div class="section-title">
	  <h2>相恋</h2>
	</div>

	<section class="row breath">
	  <div class="col-md-6">
		<div class="testblock">
          <p>
            曾经心目中的他，是个清秀干净的大男生，能够一起学习一起生活，也能一起看花看海数星星；不想现实中的他，<strong>脸上坑坑洼洼似经历了卫星冲撞般的洗礼</strong>，但撇开外貌上的差距，学习、生活与志趣方面，亲爱的都超越了期待。第一次长途旅行，是他作为领队带着基本零经验的我们单车环浙南，也是在这次旅行中，偶遇的漫天繁星让我们惊呆得说不出话来；第一次看海，是东极岛的日出和烟雨中的奇幻，尽管东海黄得让人无法接受，大自然却已给予了或是阳光倾泻或是云雾缭绕中波浪拍打岩石的地老天荒；再后来，就有各自的旅行，他赶去沐浴西藏的阳光，我选择了海南的沙滩，但始终不变的是行走、思考、在路上的心境与挑战自我、挑战世界的青春年少。
          </p>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_m.png" alt=".">
		  <p><strong>妞</strong></p>
		</div>
	  </div><! --/col-md-6 -->

	  <div class="col-md-6">
		<div class="testblock">
          玉兰花开，韶华灿烂<br>
          在最灿烂绽放的年岁<br>
          他们牵手<br>
          相恋<br>
          忘不了启真湖畔月明星稀梁祝悠扬<br>
          忘不了平湖秋月苏堤春晓树影穿梭<br>
          忘不了青海湖边花容灿烂纵马驰骋<br>
          忘不了西行路上风雨兼程衣裙漫飞<br>
          <strong>所谓相恋，春花秋月</strong><br>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_x.png" alt=".">
		  <p><strong>爷</strong></p>
		</div>
	  </div><! --/col-md-6 -->
	</section><! --/section -->

  </div><! --/container -->
</div><! --/Testimonials -->

<!-- testimonials 3 -->
<div class="highlight testimonials">
  <div class="container">
	<div class="section-title">
	  <h2>相爱</h2>
	</div>

    <section class="row breath">
	  <div class="col-md-6">
		<div class="testblock">
          <p>
            工作后，旅行的日子少了很多，出差的日子却多了不少，但毫无怨言的理解与支持，都融在柴米油盐的一日三餐中了。总有那么一个人，忙碌的时候能够帮你处理生活琐碎、能够做好饭菜等你回来，焦虑的时候能够一起畅谈人生规划、闲暇快乐之时又可以一起走南闯北，想想都好幸福。
          </p>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_m.png" alt=".">
		  <p><strong>妞</strong></p>
		</div>
	  </div><! --/col-md-6 -->

	  <div class="col-md-6">
		<div class="testblock">
          他接任了社团的会长，责任在肩<br>
          她完成了专业的转换，学业繁重<br>
          他留守紫金港<br>
          她奔赴华家池<br>
          他的社团凤凰涅磐<br>
          她的男友心力交瘁<br>
          他颓废<br>
          她陪伴<br>
          <strong>所谓相爱，不离不弃</strong><br>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_x.png" alt=".">
		  <p><strong>爷</strong></p>
		</div>
	  </div><! --/col-md-6 -->
	</section><! --/section -->


  </div><! --/container -->
</div><! --/highlight Testimonials -->

<!-- testimonials 4 -->
<div class="testimonials">
  <div class="container">
	<div class="section-title">
	  <h2>相知</h2>
	</div>

	<section class="row breath">
	  <div class="col-md-6">
		<div class="testblock">
          <p>
            曾经的我们也有过争吵，有过疑虑，但最困难的时候，是他一直耐心的陪伴与引导；开心的时候，又是他孩童般的欢笑和嬉闹。脑海里一直刻着相识之初他拉着我的手在树林中穿梭的感觉，尽管障碍重重，两个人手牵手就可以这样一直走下去，从黑夜走到白天，从荆棘荒原走到童话中的花园王国。或许我们的爱情，在那一刻就已经注定了呢，没有太多的波澜起伏与惊天动地，但凭着双方的努力与坚守，我们共同开拓了人生旅途。好感谢上苍，给了我这样一个他。
          </p>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_m.png" alt=".">
		  <p><strong>妞</strong></p>
		</div>
	  </div><! --/col-md-6 -->

	  <div class="col-md-6">
		<div class="testblock">
          他渐渐恢复<br>
          她慢慢放心<br>
          他再次踏上旅程<br>
          她还是继续陪伴<br>
          忘不了风雨泥泞神农架路险山高<br>
          忘不了毡帽古镇绍兴酒回味悠长<br>
          忘不了朝露清晨天目山月圆夜话<br>
          <strong>所谓相知，风雨同行</strong><br>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_x.png" alt=".">
		  <p><strong>爷</strong></p>
		</div>
	  </div><! --/col-md-6 -->
	</section><! --/section -->

  </div><! --/container -->
</div><! --/Testimonials -->

<!-- testimonial 5 -->
<div class="highlight testimonials">
  <div class="container">
	<div class="section-title">
	  <h2>相守</h2>
	</div>

	<section class="row breath">
	  <div class="col-md-6">
		<div class="testblock">
          <p>
            对于即将到来的婚礼，有过期待有过设想，最好是面朝大海、春暖花开，至少也要空旷的山谷里，阳光倾泻到每个人的脸上，清风还能送来阵阵芬芳。只是这样的场景，对于我们俩人来说似乎已经在一次次的旅行中无数次呈现，只是没有穿上梦幻的白纱，真穿上了，也只是走走仪式与过场，哪能穿着大白纱自在奔跑呢？
          </p>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_m.png" alt=".">
		  <p><strong>妞</strong></p>
		</div>
	  </div><! --/col-md-6 -->

	  <div class="col-md-6">
		<div class="testblock">
          他忙于学业<br>
          她准备考研<br>
          她给他占座<br>
          他帮她暖手<br>
          她订票<br>
          他背包<br>
          鼓浪屿上<br>
          琴声悠扬<br>
          <strong>所谓相守，初心不改</strong><br>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_x.png" alt=".">
		  <p><strong>爷</strong></p>
		</div>
	  </div><! --/col-md-6 -->
	</section><! --/section -->

  </div><! --/container -->
</div><! --/highlight Testimonials -->

<!-- testimonials 6 -->
<div class="testimonials">
  <div class="container">
	<div class="section-title">
	  <h2>相伴</h2>
	</div>

	<section class="row breath">
	  <div class="col-md-6">
		<div class="testblock">
          <p>
            鱼与熊掌不可得兼，如此的造梦成本对于白手起家的我们来说，实在有些支付不起。所以婚礼更多的是出于家长的要求，不能免俗就让家长们去折腾吧，彻彻底底地俗一次，就像没有挂过科的人生是不完整的，配合着家庭演场大戏也能拓展拓展我们的人生履历，就当是一次新的旅行，<strong>我们一起走在路上，有你有我，还有大家。</strong>
          </p>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_m.png" alt=".">
		  <p><strong>妞</strong></p>
		</div>
	  </div><! --/col-md-6 -->

	  <div class="col-md-6">
		<div class="testblock">
          他去了北京<br>
          她也去了北京<br>
          他工作<br>
          她读书<br>
          清晨，他睁眼醒来，是她精心准备早餐的忙碌身影<br>
          傍晚，她翘首望去，是他辛苦工作归来的仆仆风尘<br>
          <strong>所谓相伴，柴米油盐</strong><br>
        </div>
		<div class="clientblock">
		  <img src="assets/gravatar_x.png" alt=".">
		  <p><strong>爷</strong></p>
		</div>
	  </div><! --/col-md-6 -->
	</section><! --/section -->

  </div><! --/container -->
</div><! --/Testimonials -->

<main class="footercta" role="main">
  <div class="container">
	<div class="section-title">
      <h1>所谓相行，即是人生</h1>
	</div>

	<section class="row breath">
	  <div id="invitation" class="col-md-6">
        <% @invitation = Invitation.new %>
        <%= render "form"%>
        <figure id="invitation-image" style="display: none">
          <img src="/images/paint/20.jpg"></img>
          <h3>祝君安</h3>
        </figure>
	  </div><! --/col-md-6 -->

	  <div class="col-md-6">
        <h4>关于婚礼</h4>
        <p>
          共两场，新娘出门宴，有宴无仪式，新郎摆婚宴，新人演大戏。新郞家乡不比京江浙沪，山沟沟里交通不便，故从北京或其余外地过去的朋友，麻烦9月30日抵达宽城，家里已安排好晚饭和宾馆住宿。
        </p>
        <h4>关于礼金</h4>
        <p>
          作为工薪一族和曾经的穷苦学生，我们深知大家手捧红色炸弹的复杂心情。因此新人自作主张提供“打欠条”和“寄贺卡”的方式，大伙云淡风清，心意永存。寄贺卡的朋友请私信新人索要地址，打欠条的朋友要记住，有朝一日我们会完璧归赵的哦。
        </p>
	  </div><! --/col-md-6 -->
	</section><! --/section -->
  </div><! --/container -->
</main><! --/main -->

<script src="assets/pace.js"></script>
<script src="assets/bootstrap.js"></script>
<script src="assets/easing.js"></script>
<script src="assets/nicescroll.js"></script>

<script>
 $(function() {
   $('.scrollto, .gototop').bind('click',function(event){
	 var $anchor = $(this);
	 $('html, body').stop().animate({
       scrollTop: $($anchor.attr('href')).offset().top
     }, 1500,'easeInOutExpo');
     event.preventDefault();
   });
 });
</script>